<?php $this->layout('layout::default', ['title' => 'Etusivu']) ?>
<div class="app-content">
  <div class="media">
    <img class="mr-3 rounded-circle" src="/images/jermu-bio.png">
    <div class="media-body">
      <h2 class="cover-heading">Suojaa sivusi.</h2>
      <p class="lead h5">Kansi on yhden sivun mallipohja yksinkertaisten ja kauniiden kotisivujen rakentamiseen. Voit ladata, muokata tekstiä ja lisätä oman koko näytön taustakuvan tehdäksesi sen omaksi.</p>
      <p class="lead">
        <a href="#" class="btn btn-sm btn-secondary">Lisätietoja</a>
      </p>
    </div>
  </div>



</div>
