<nav class="navbar navbar-expand-lg navbar-light justify-content-between">
  <div class="container">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<?=$this->url('home.page')?>">
        <strong>jahlgren.eu</strong>
    </a>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <div class="nav">
        <a class="nav-item nav-link" href="<?=$this->url('home.page')?>">
            <i class="fas fa-home"></i> Home</a>
        <a class="nav-item nav-link" href="<?=$this->url('css.page')?>">
            <i class="fas fa-user-graduate"></i> Learning</a>
        <a class="nav-item nav-link disabled" href="#">
            <i class="fas fa-envelope-square"></i> Contact</a>
      </div>
    </div>

  </div>
</nav>
